// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIu_6z03BowsNo2NXTOIf-ostWv9xdYio',
    appId: '1:1078145163561:web:your-web-app-id',
    messagingSenderId: '1078145163561',
    projectId: 'walkie-e86f4',
    authDomain: 'walkie-e86f4.firebaseapp.com',
    storageBucket: 'walkie-e86f4.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIu_6z03BowsNo2NXTOIf-ostWv9xdYio',
    appId: '1:1078145163561:android:01c6ac4334e8b71ce91738',
    messagingSenderId: '1078145163561',
    projectId: 'walkie-e86f4',
    storageBucket: 'walkie-e86f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIu_6z03BowsNo2NXTOIf-ostWv9xdYio',
    appId: '1:1078145163561:ios:your-ios-app-id',
    messagingSenderId: '1078145163561',
    projectId: 'walkie-e86f4',
    storageBucket: 'walkie-e86f4.firebasestorage.app',
    iosBundleId: 'com.example.walkie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIu_6z03BowsNo2NXTOIf-ostWv9xdYio',
    appId: '1:1078145163561:ios:your-macos-app-id',
    messagingSenderId: '1078145163561',
    projectId: 'walkie-e86f4',
    storageBucket: 'walkie-e86f4.firebasestorage.app',
    iosBundleId: 'com.example.walkie',
  );
}
